### ISSUE TITLE
Bad content format should cause errors.

### ISSUE THREAD

**Issue by stefan-dimitrov** [stefan-dimitrov/grunt-i18n-compile#3]
When file content cannot be converted correctly the plugin should throw an error indicating the problem.

Currently in some cases it would convert incorrectly without any warning.
One such case is:

``` yaml
COUNTRY:
  SWITZERLAND:
    NAME:
      en: Switzerland
      bg: Швейцария
    LANGUAGE:
      en: German
      bg: Немски
      SECOND:
        en: French
        bg: Френски
  ...
```

where the translations would be incomplete:

``` json
{
  "en": {
    "COUNTRY": {
      "SWITZERLAND": {
        "NAME": "Switzerland",
        "LANGUAGE": {
          "SECOND": "French"
        }
      }
    }
  },
  "bg": {
    "COUNTRY": {
      "SWITZERLAND": {
        "NAME": "Швейцария",
        "LANGUAGE": {
          "SECOND": "Френски"
        }
      }
    }
  }
}
```

(Impossible to have `"LANGUAGE"` with both a string value and an object value at the same time)
