### ISSUE TITLE
Should be able to compile lists(arrays) in translations, not only strings

### ISSUE THREAD

**Issue by stefan-dimitrov** [stefan-dimitrov/grunt-i18n-compile#4]
Translations with lists as their values should also be converted.
Example case:

``` yaml
MY_TEMPLATES:
    en: ['value 1', 'value 2', 'value 3']
    bg: ['стойност 1', 'стойност 2', 'стойност 3']
```

should be converted to:
lang_en.json

``` json
"MY_TEMPLATES": ["value 1", "value 2", "value 3"]
```

lang_bg.json

``` json
"MY_TEMPLATES": ["стойност 1", "стойност 2", "стойност 3"]
```

But instead, currently those values are omitted for conversion.
