### ISSUE TITLE
Misleading error message for duplicated mapping keys

### ISSUE THREAD

**Issue by stefan-dimitrov** [stefan-dimitrov/grunt-i18n-compile#8]
When there are duplicated keys in a yaml file the error message is pointing to the key following the duplicated one.

When we have in a yaml file:

``` yaml
...
LABEL:
  en: User
  es: Usuario
LABEL:
  en: User
  es: Usuario
DROPDOWN:
  EDIT:
    en: Edit
    es: Editar
...
```

The error message is:

``` sh
Warning: duplicated mapping key in "path/to/translation.yaml" at line 11, column 5:
        DROPDOWN:
        ^ 
```

but the duplicated key is the one above - `LABEL:`
